steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend-IU777", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend-IU777"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "backend-IU777",
        "--image", "gcr.io/$PROJECT_ID/backend-IU777",
        "--timeout", "1000s",
        "--port", "3000",
        "--region", "us-central1",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY